---
- name: Install todotxt from apt repositories
  become: yes
  package:
    name: todotxt-cli
    state: present
  when: ansible_facts['distribution'] in debian_like_distributions

- block:
    - name: Install todotxt from AUR
      kewlfft.aur.aur:
        name: todotxt
        use: makepkg
        state: present
    - name: Create symlink to make 'todo.sh' available as 'todo-txt'
      become: yes
      file:
        src: /usr/bin/todo.sh
        path: /usr/bin/todo-txt
        state: link      
  when: ansible_facts['distribution'] in arch_like_distributions

- name: Symlink todotxt configuration files
  include_tasks: make_symlinks.yaml
  vars:
    symlinks:
      - { dest: '~/.config/todotxt', src_name: 'todotxt' }
