---
- name: Install user CLI tools
  become: yes
  package:
    name:
      # important ones
      - dnsutils
      - git
      - htop
      - iftop
      - iotop
      - nano
      - ncdu
      - nmap
      - sudo
      - tmux
      - wget

      # others
      - abcde
      - cpulimit
      - curl
      - foremost
      - fzf
      - hugo
      - iperf3
      - jq
      - neofetch
      - pandoc
      - parallel
      - pdfgrep
      - ripgrep
      - smartmontools
      - smbclient
      - sox
      - sshfs
      - traceroute
      - tree
      - unzip
      - wavemon
    state: present

- name: Install user CLI tools from apt repositories
  become: yes
  package:
    name:
      # important ones
      - iputils-ping
      - 7zip
      - unrar-free
      - network-manager

      # others
      - cpufrequtils
      - webp
      - wireless-tools
    state: present
  when: ansible_facts['distribution'] in debian_like_distributions

- block:
  - name: Install user CLI tools from Arch core/extra repositories
    become: yes
    package:
      name:
        # important ones
        - iputils
        - p7zip
        - unrar
        - networkmanager

        # others
        - cpupower
        - libwebp
        - parallel
        - wireless_tools
      state: present
  - name: Install user CLI tools from AUR
    kewlfft.aur.aur:
      name: abcde
      use: makepkg
      state: present
  when: ansible_facts['distribution'] in arch_like_distributions

- name: Symlink abcde configuration file
  include_tasks: make_symlinks.yaml
  vars:
    symlinks:
      - { dest: '~/.abcde.conf', src_name: 'abcde/.abcde.conf' }
