---
- name: Get machine ID from environment variable
  set_fact: machine_id="{{ lookup('env', 'MACHINE_ID') }}"

- name: Symlink device-specific LVDS screens script
  include_tasks: make_symlinks.yaml
  vars:
    symlinks:
      - { dest: '~/.config/scripts/lvds_screens.py', src_name: 'device_specific/{{ machine_id }}/lvds_screens.py' }