---
- name: Install tools for tablet devices on Debian/Ubuntu
  block:
    - name: Notify about manual installation for Debian/Ubuntu
      debug:
        msg: |
          Install manually:
          - https://github.com/martin-ueding/thinkpad-scripts
  when: ansible_facts['distribution'] in debian_like_distributions

- name: Install tools for tablet devices on Arch/Manjaro
  kewlfft.aur.aur:
    name:
      - thinkpad-scripts
    use: makepkg
    state: present
  when: ansible_facts['distribution'] in arch_like_distributions

- name: Symlink tablet device configuration files
  include_tasks: make_symlinks.yaml
  vars:
    symlinks:
      - { dest: '~/.config/thinkpad-scripts/hooks/postrotate', src_name: 'thinkpad-scripts/postrotate' }