---
- name: Install GUI tools
  become: yes
  package:
    name:
      - arandr
      - clusterssh
      - diffpdf
      - firefox
      - gimp
      - gnucash
      - gparted
      - keepassxc
      - libreoffice
      - meld
      - obs-studio
      - openscad
      - peek
      - remmina
      - texstudio
      - vlc
      - x2goclient
    state: present

- name: Install GUI tools for Debian/Ubuntu
  block:
    - name: Install GUI tools from apt repositories
      become: yes
      package:
        name:
          - anki
          - jabref
          - pdfsam
          - virtualbox
          - xournal
        state: present
    - name: Notify about manual installation for Debian/Ubuntu
      debug:
        msg: >
          Install manually:
          - Synology Drive
          - https://github.com/VSCodium/vscodium
  when: ansible_facts['distribution'] in debian_like_distributions

- name: Install GUI tools for Arch/Manjaro
  block:
    - name: Install GUI tools from AUR
      kewlfft.aur.aur:
        name:
          - anki-official-binary-bundle
          - jabref-latest
          - google-chrome
          - pdfsam
          - synology-drive
          - vscodium-bin
        use: makepkg
        state: present
    - name: Install GUI tools from Arch core/extra repositories
      become: yes
      package:
        name:
          - xournalpp
          - virtualbox
          #- virtualbox-host-modules-arch
        state: present
  when: ansible_facts['distribution'] in arch_like_distributions

- name: Symlink GUI tool configuration files
  include_tasks: make_symlinks.yaml
  vars:
    symlinks:
      - { dest: '~/.config/VSCodium/User/keybindings.json', src_name: 'vscodium/keybindings.json' }
      - { dest: '~/.config/VSCodium/User/settings.json', src_name: 'vscodium/settings.json' }
