#!/bin/bash

# Source: https://raw.githubusercontent.com/mbrubeck/todo.txt-cli/master/todo.actions.d/edit
# It's GPL licensed, so: http://www.gnu.org/copyleft/gpl.html

case $1 in
"usage")
  echo "$(basename $0) [BASENAME]"
  echo "  Open \$TODO_DIR/BASENAME.txt in \$EDITOR."
  echo "  If BASENAME is not given, defaults to 'todo'."
  ;;
*)
  if [[ -z $2 ]]; then
    FILE=$TODO_FILE
  else
    # Minor modification: remove .txt extension here
    FILE=$TODO_DIR/$2
  fi
  if [ -n "$EDITOR" ]; then
    $EDITOR $FILE
  else
    echo "Error: The EDITOR environment variable is not set"
  fi
  ;;
esac
